basePath: /abizerlokhandwala/devflows-api/1.0.0
definitions:
  data_service:
    properties:
      domain_id:
        type: integer
      id:
        type: integer
      model_config:
        type: string
      repo_name:
        type: string
    type: object
  deployment_status:
    properties:
      flow_id:
        type: integer
      id:
        type: integer
      prod_version_id:
        type: integer
      stage_version_id:
        type: integer
    type: object
  domain:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  flow:
    properties:
      id:
        type: integer
      name:
        type: string
      product_id:
        type: integer
    type: object
  product:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  task:
    properties:
      domain_id:
        type: integer
      env_variables:
        type: string
      framework:
        type: string
      id:
        type: integer
      input_schema:
        type: string
      is_bootstrapped:
        type: boolean
      is_published:
        type: boolean
      name:
        type: string
      output_schema:
        type: string
      path:
        type: string
      port:
        type: string
      repo_name:
        type: string
    type: object
host: virtserver.swaggerhub.com
info:
  title: Devflow API
  version: 1.0.0
paths:
  /domains:
    get:
      description: |
        get all domains
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: search results matching criteria
          schema:
            properties:
              domains:
                items:
                  type: string
                type: array
            type: object
        '400':
          description: bad input parameter
      summary: get all domains
      tags:
        - domain
    post:
      consumes:
        - application/json
      description: Adds a new domain
      parameters:
        - in: body
          name: body
          schema:
            properties:
              name:
                description: Domain name
                type: string
            type: object
      produces:
        - application/json
      responses:
        '201':
          description: domain created
          schema:
            properties:
              id:
                type: integer
            type: object
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing domain already exists
      summary: add domain
      tags:
        - domain
  '/domains/{id}/model':
    get:
      description: |
        get data model by domain name
      parameters:
        - in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: search results matching criteria
          schema:
            properties:
              model_config:
                type: string
              repo_name:
                type: string
            type: object
        '400':
          description: bad input parameter
      summary: get model of a domain
      tags:
        - data model
    post:
      consumes:
        - application/json
      description: Adds a new data model for the given domain
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: body
          schema:
            properties:
              model_config:
                type: string
            type: object
      responses:
        '201':
          description: data model created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing data model already exists
      summary: add data model of a domain
      tags:
        - data model
  /flows:
    get:
      description: |
        get flow by product name
      parameters:
        - description: name of the product
          in: query
          name: product_name
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: search results matching criteria
          schema:
            properties:
              flows:
                items:
                  properties:
                    name:
                      type: string
                  type: object
                type: array
            type: object
        '400':
          description: bad input parameter
      summary: get all flows part of a product
      tags:
        - flow
    post:
      consumes:
        - application/json
      description: Adds a new flow
      parameters:
        - in: body
          name: body
          schema:
            properties:
              flow_json:
                type: object
              name:
                type: string
              product:
                type: string
            type: object
      produces:
        - application/json
      responses:
        '201':
          description: flow created
          schema:
            properties:
              id:
                type: integer
            type: object
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing flow already exists
      summary: add flow
      tags:
        - flow
  '/flows/{id}':
    get:
      description: |
        get flow by id
      parameters:
        - in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: search results matching criteria
          schema:
            properties:
              flow_json:
                type: object
              id:
                type: integer
              name:
                type: string
              prod_version:
                type: string
              product:
                type: string
              staging_version:
                type: string
            type: object
        '400':
          description: bad input parameter
      summary: get flow
      tags:
        - flow
    put:
      consumes:
        - application/json
      description: Updates a flow
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: body
          schema:
            properties:
              flow_json:
                type: object
              name:
                type: string
              product:
                type: string
            type: object
      responses:
        '204':
          description: flow updated
        '400':
          description: 'invalid input, object invalid'
      summary: update flow
      tags:
        - flow
  '/flows/{id}/deploy/{env}':
    put:
      consumes:
        - application/json
      description: env parameter can take the values prod and dev
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: path
          name: env
          required: true
          type: string
        - in: body
          name: body
          schema:
            properties:
              flow_json:
                type: object
              name:
                type: string
              product:
                type: string
            type: object
      responses:
        '201':
          description: flow deployed
        '400':
          description: 'invalid input, object invalid'
      summary: deploy flow to environment
      tags:
        - deploy flow to environment
  '/flows/{id}/load/{version}':
    get:
      description: version is the version of the flow
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: path
          name: version
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: search results matching criteria
          schema:
            properties:
              flow_json:
                type: object
              name:
                type: string
              product:
                type: string
            type: object
        '400':
          description: bad input parameter
      summary: load flow of given environment
      tags:
        - load flow
  '/flows/{id}/status':
    get:
      description: get deployment status of flow with given id (true/false)
      parameters:
        - in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: true/false
          schema:
            properties:
              status:
                type: boolean
            type: object
        '400':
          description: 'invalid input, object invalid'
      summary: get deployment status of flow with given id
      tags:
        - status
  '/flows/{id}/versions':
    get:
      description: get all versions of a flow
      parameters:
        - in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: get all versions of a flow
          schema:
            properties:
              versions:
                items:
                  type: string
                type: array
            type: object
        '400':
          description: 'invalid input, object invalid'
      summary: get all versions of a flow
      tags:
        - flow
  /products:
    get:
      description: |
        get all products by name
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: search results matching criteria
          schema:
            properties:
              products:
                items:
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                  type: object
                type: array
            type: object
        '400':
          description: bad input parameter
      summary: get all products
      tags:
        - product
    post:
      consumes:
        - application/json
      description: Adds a new product
      parameters:
        - in: body
          name: body
          schema:
            properties:
              name:
                type: string
            type: object
      responses:
        '201':
          description: product created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing product already exists
      summary: add product
      tags:
        - product
  /tasks:
    get:
      description: |
        get all tasks part of a domain
      parameters:
        - description: name of the domain
          in: query
          name: domain_name
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: search results matching criteria
          schema:
            properties:
              tasks:
                items:
                  properties:
                    framework:
                      type: string
                    id:
                      type: integer
                    name:
                      type: string
                    path:
                      type: string
                    repo_name:
                      type: string
                  type: object
                type: array
            type: object
        '400':
          description: bad input parameter
      summary: get all tasks part of a domain
      tags:
        - task
    post:
      consumes:
        - application/json
      description: Adds a new task under a particular domain
      parameters:
        - in: body
          name: body
          schema:
            properties:
              domain_name:
                type: string
              framework:
                type: string
              input_schema:
                properties:
                  args:
                    items:
                      properties:
                        variable_name:
                          type: string
                        variable_type:
                          type: string
                      type: object
                    type: array
                  num_args:
                    type: integer
                type: object
              is_published:
                type: boolean
              name:
                type: string
              output_schema:
                properties:
                  args:
                    items:
                      properties:
                        variable_name:
                          type: string
                        variable_type:
                          type: string
                      type: object
                    type: array
                  num_args:
                    type: integer
                type: object
              path:
                type: string
              repo_name:
                type: string
            type: object
      produces:
        - application/json
      responses:
        '201':
          description: task created
          schema:
            properties:
              id:
                type: integer
            type: object
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing task already exists
      summary: add task
      tags:
        - task
  '/tasks/{id}':
    get:
      description: |
        get task by id
      parameters:
        - in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: search results matching criteria
          schema:
            properties:
              domain_name:
                type: string
              framework:
                type: string
              id:
                type: integer
              input_schema:
                properties:
                  args:
                    items:
                      properties:
                        variable_name:
                          type: string
                        variable_type:
                          type: string
                      type: object
                    type: array
                  num_args:
                    type: integer
                type: object
              is_bootstrapped:
                type: boolean
              is_published:
                type: boolean
              name:
                type: string
              output_schema:
                properties:
                  args:
                    items:
                      properties:
                        variable_name:
                          type: string
                        variable_type:
                          type: string
                      type: object
                    type: array
                  num_args:
                    type: integer
                type: object
              path:
                type: string
              repo_name:
                type: string
              version:
                type: number
            type: object
        '400':
          description: bad input parameter
      summary: get task
      tags:
        - task
    put:
      consumes:
        - application/json
      description: Updates a task under a particular domain
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: body
          schema:
            properties:
              domain_name:
                type: string
              framework:
                type: string
              input_schema:
                properties:
                  args:
                    items:
                      properties:
                        variable_name:
                          type: string
                        variable_type:
                          type: string
                      type: object
                    type: array
                  num_args:
                    type: integer
                type: object
              is_published:
                type: boolean
              name:
                type: string
              output_schema:
                properties:
                  args:
                    items:
                      properties:
                        variable_name:
                          type: string
                        variable_type:
                          type: string
                      type: object
                    type: array
                  num_args:
                    type: integer
                type: object
              path:
                type: string
              repo_name:
                type: string
            type: object
      responses:
        '204':
          description: task updated
        '400':
          description: 'invalid input, object invalid'
      summary: update task
      tags:
        - task
  '/tasks/{id}/version':
    get:
      description: |
        get all versions of a task
      parameters:
        - in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: search results matching criteria
          schema:
            properties:
              versions:
                items:
                  type: number
                type: array
            type: object
        '400':
          description: bad input parameter
      summary: get all task versions
      tags:
        - task
schemes:
  - https
swagger: '2.0'
x-components: {}

