# Generated by Django 3.0.2 on 2020-01-29 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='domain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'domain',
                'verbose_name_plural': 'domains',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='flow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'flow',
                'verbose_name_plural': 'flows',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('env_variables', models.CharField(max_length=255)),
                ('framework', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('input_schema', models.CharField(max_length=255)),
                ('is_bootstrapped', models.BooleanField()),
                ('is_published', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('output_schema', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('repo_name', models.CharField(max_length=255)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.domain')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='flow_version',
            fields=[
                ('flow_json', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('version', models.FloatField()),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.flow')),
            ],
            options={
                'verbose_name': 'flow_version',
                'verbose_name_plural': 'flow_versions',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.product'),
        ),
        migrations.CreateModel(
            name='deployment_status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.flow')),
                ('prod_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='new_app.flow_version')),
                ('stage_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.flow_version')),
            ],
            options={
                'verbose_name': 'deployment_status',
                'verbose_name_plural': 'deployment_statuss',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='data_service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('model_config', models.CharField(max_length=255)),
                ('repo_name', models.CharField(max_length=255)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.domain')),
            ],
            options={
                'verbose_name': 'data_service',
                'verbose_name_plural': 'data_services',
                'ordering': ('-id',),
            },
        ),
    ]
